name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: compiling advance_code_with_cli.cpp
      run: gcc advance_code_with_cli.cpp -o a
    - name: compiling C++Project_water_Quality_Checker.cpp
      run: gcc C++Project_water_Quality_Checker.cpp -o b
